version: '3.9'

services:
  db:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/db_password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main-network
    secrets:
      - db_password

  backend-rust:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: /run/secrets/db_password
    links:
      - db
    secrets:
      - db_password
    depends_on:
      - db
    networks:
      - main-network

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  postgres-data:
    name: postgres-data

networks:
  main-network:
    name: main-network
    driver: bridge

